name: Build
on:
  push:
    tags:
      - '*'
jobs:
  build_and_push:
    name: Build  & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        run: docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build . -t codebeans/laravel:${GITHUB_REF##*/} -t codebeans/laravel:latest
      - name: Push
        run: docker push codebeans/laravel:${GITHUB_REF##*/} --all-tags